;;; smoke-ja4.el --- JA-4 device gate: the org engine -*- lexical-binding: t; -*-

;; Four hardware claims over ONE connection, one throwaway owner "ja4":
;;   Q1 query: a device tap runs the vetted grammar ((todo "TODO")
;;      through `jetpacs-org-parse-query') over a generated fixture
;;      file and the hit count renders from a token-minted set.  The
;;      handler mints TWICE into the same (owner,set) — the replace
;;      sweep makes mint A's tokens the stale bait for Q4.
;;   Q2 toggle: token -> ref -> `jetpacs-org-toggle-todo' with the
;;      state note flushed inline (DONE(!) + org-log-into-drawer); the
;;      fixture FILE re-read from disk carries "* DONE" and the
;;      `- State "DONE"' LOGBOOK line.
;;   Q3 capture: `jetpacs-org-capture-run' through the filled-copy
;;      binding lands the phone-supplied title in the file, no %^
;;      residue, no lingering CAPTURE- buffer.
;;   Q4 stale: a tap whose args carry a swept (pre-re-mint) token
;;      answers `stale' (SPEC 14.5), and owner teardown sweeps the
;;      live set too.
;;
;; JA-4 audit Batch 4 (P1-8/P1-9/P1-10) moved the token/status
;; contract; this harness asserts the NEW shape:
;;   - Q1 additionally proves the ATOMIC mint on the live flow: a mint
;;      whose last ref is hostile signals `jetpacs-org-refused' and
;;      leaves mint B's live generation resolving (pre-Batch-4 that
;;      mint DESTROYED the live set and Q2's tap would answer stale).
;;   - ja4.toggle maps engine conditions through
;;      `jetpacs-org-refusal-disposition' — rejected / stale /
;;      retry->`jetpacs-retry-later' — instead of a hand-kept
;;      condition-case pair that predates `jetpacs-org-unavailable'.
;;
;; Batch has no command loop, so idleness never begins and
;; `run-with-idle-timer' saves never fire on their own; the harness
;; fires the armed timer by hand (`smoke-j4--flush-idle-saves') — the
;; debounce and refuse-on-supersession semantics are pinned in ERT.
;;
;; Run with the app open and `adb forward tcp:8765 tcp:8765'.

(require 'ebp)
(require 'org)
(require 'org-capture)
(require 'jetpacs-widgets)
(require 'jetpacs-async)
(require 'jetpacs-surfaces)
(require 'jetpacs-shell)
(require 'jetpacs-org)

(defvar smoke-j4--fails 0)
(defun smoke-j4--check (label ok &optional detail)
  (princ (format "%-52s %s%s\n" label (if ok "PASS" "FAIL")
                 (if detail (format "  (%s)" detail) "")))
  (unless ok (setq smoke-j4--fails (1+ smoke-j4--fails))))
(defun smoke-j4--drain (secs &optional stop-fn)
  (let ((deadline (+ (float-time) secs)))
    (while (and (< (float-time) deadline)
                (not (and stop-fn (funcall stop-fn))))
      (accept-process-output nil 0.1))))
(defun smoke-j4--mark (m) (princ (concat m "\n")) (message "%s" m))

;;; Fixture: generated bytes only, under a root the module accepts.

(defvar smoke-j4--dir (make-temp-file "smoke-ja4" t))
(defvar smoke-j4--file (expand-file-name "ja4.org" smoke-j4--dir))
(with-temp-file smoke-j4--file
  (insert "* TODO Water the plants\n* TODO Fix the gate\n* DONE Old chore\n"))
(setq jetpacs-org-roots (list smoke-j4--dir)
      org-agenda-files (list smoke-j4--file)
      org-todo-keywords '((sequence "TODO" "|" "DONE(!)"))
      org-log-into-drawer t
      org-capture-templates `(("j" "JA4" entry (file ,smoke-j4--file)
                               "* TODO %^{Title}\n%?")))

(defun smoke-j4--file-text ()
  (with-temp-buffer (insert-file-contents smoke-j4--file) (buffer-string)))

(defun smoke-j4--flush-idle-saves ()
  (dolist (tm (copy-sequence timer-idle-list))
    (when (eq (timer--function tm) #'jetpacs-org--save-now)
      (cancel-timer tm)
      (apply (timer--function tm) (timer--args tm)))))

;;; Owner, screen, handlers.

(defvar smoke-j4--stage 'start)
(defvar smoke-j4--count nil)
(defvar smoke-j4--live-token nil)
(defvar smoke-j4--stale-token nil)
(defvar smoke-j4--toggled nil)
(defvar smoke-j4--stale-answer nil)

(with-jetpacs-owner "ja4"
  (jetpacs-shell-define-root
   "ja4"
   (lambda ()
     (jetpacs-scaffold
      :body
      (if (eq smoke-j4--stage 'start)
          (jetpacs-column
           (jetpacs-text "JA-4 org smoke" :style "headline")
           (jetpacs-button "Run query" (jetpacs-action "ja4.query")))
        (jetpacs-column
         (jetpacs-text (format "%d TODOs" smoke-j4--count) :style "headline")
         (jetpacs-button "Toggle first TODO"
                         (jetpacs-action "ja4.toggle"
                                         :args (list :token smoke-j4--live-token)))
         (jetpacs-button "Capture from phone" (jetpacs-action "ja4.capture"))
         (jetpacs-button "Stale tap"
                         (jetpacs-action "ja4.stale"
                                         :args (list :token smoke-j4--stale-token))))))))

  (jetpacs-defaction "ja4.query"
    (lambda (_args _params)
      (let* ((tree (jetpacs-org-parse-query "(todo \"TODO\")"))
             (refs (jetpacs-org-query "ja4" tree #'jetpacs-org-ref-at-point))
             (mint-a (jetpacs-org-ref-tokens refs :set "q" :owner "ja4"))
             (mint-b (jetpacs-org-ref-tokens refs :set "q" :owner "ja4")))
        (setq smoke-j4--stale-token (car mint-a)   ; swept by mint B
              smoke-j4--live-token (car mint-b)
              smoke-j4--count (length refs)
              smoke-j4--stage 'ready)
        (jetpacs-flow-continue
         (lambda ()
           (condition-case err
               (with-jetpacs-owner "ja4" (jetpacs-shell-push "ja4"))
             (error (message "smoke-ja4: re-push failed: %s"
                             (jetpacs--error-label err))))))
        'accepted)))

  (jetpacs-defaction "ja4.toggle"
    (lambda (args _params)
      (let ((ref (jetpacs-org-token-ref (plist-get args :token) :owner "ja4")))
        (if (null ref) 'stale
          ;; The Batch-4 status map, via the helper the engine ships:
          ;; rejected / stale come back as statuses; retry concludes
          ;; the action with 1500 event-retry (the record survives).
          (condition-case err
              (progn (jetpacs-org-toggle-todo ref "ja4" "DONE")
                     (setq smoke-j4--toggled t)
                     'accepted)
            ((jetpacs-org-refused jetpacs-org-unavailable
                                  jetpacs-org-unresolved)
             (pcase (jetpacs-org-refusal-disposition err)
               ('retry (jetpacs-retry-later))
               (status status))))))))

  (jetpacs-defaction "ja4.capture"
    (lambda (_args _params)
      (jetpacs-flow-continue
       (lambda ()
         (condition-case err
             (jetpacs-org-capture-run "j" '(("Title" . "From the phone")
                                            ("Headline" . "captured on device")))
           (error (message "smoke-ja4: capture failed: %s"
                           (error-message-string err))))))
      'accepted))

  (jetpacs-defaction "ja4.stale"
    (lambda (args _params)
      (let ((ref (jetpacs-org-token-ref (plist-get args :token) :owner "ja4")))
        (setq smoke-j4--stale-answer (if ref 'accepted 'stale))
        smoke-j4--stale-answer))))

;;; The run.

(let ((client
       (jetpacs-connect
        "127.0.0.1" 8765
        :client-name "wsl-emacs" :client-version "30.1"
        :pairing-id "101112131415161718191a1b1c1d1e1f"
        :token (ebp-decode-pairing-token "AAECAwQFBgcICQoLDA0ODw")
        :receipt-file (make-temp-file "smoke-j4-receipts"))))

  (smoke-j4--drain 20 (lambda () (jetpacs-connected-p)))
  (smoke-j4--check "session reaches READY" (jetpacs-connected-p))

  (when (jetpacs-connected-p)
    (with-jetpacs-owner "ja4" (jetpacs-shell-push "ja4"))
    (smoke-j4--drain 2)

    ;; Q1 query + double mint.
    (smoke-j4--mark "Q1-TAP-QUERY")
    (smoke-j4--drain 150 (lambda () smoke-j4--count))
    (smoke-j4--check "query matched the two TODOs (DONE excluded)"
                     (equal smoke-j4--count 2)
                     (format "%S" smoke-j4--count))
    (smoke-j4--check "tokens minted opaque"
                     (and (stringp smoke-j4--live-token)
                          (string-prefix-p "o" smoke-j4--live-token)
                          (not (string-search smoke-j4--file
                                              smoke-j4--live-token))))
    (smoke-j4--check "live token resolves to a fixture ref"
                     (let ((ref (jetpacs-org-token-ref smoke-j4--live-token
                                                       :owner "ja4")))
                       (and ref (equal (plist-get ref :file)
                                       (file-truename smoke-j4--file)))))
    (smoke-j4--check "pre-re-mint token already swept (replace sweep)"
                     (null (jetpacs-org-token-ref smoke-j4--stale-token
                                                  :owner "ja4")))
    ;; Batch 4 / P1-8: a FAILED mint into the same (owner,set) is
    ;; all-or-nothing — it must leave mint B's live generation intact,
    ;; or Q2's tap below would answer stale against a dead token.
    (smoke-j4--check "failed mint leaves the live generation intact"
                     (let ((live (jetpacs-org-token-ref
                                  smoke-j4--live-token :owner "ja4")))
                       (and live
                            (eq 'jetpacs-org-refused
                                (condition-case err
                                    (progn
                                      (jetpacs-org-ref-tokens
                                       (list live
                                             '(:id nil
                                               :file "/ssh:evil:/x.org"
                                               :pos 1 :headline ""))
                                       :set "q" :owner "ja4")
                                      'no-signal)
                                  (error (car err))))
                            (and (jetpacs-org-token-ref
                                  smoke-j4--live-token :owner "ja4")
                                 t))))
    (smoke-j4--drain 3)

    ;; Q2 toggle through the token, then the file re-read from disk.
    (smoke-j4--mark "Q2-TAP-TOGGLE")
    (smoke-j4--drain 150 (lambda () smoke-j4--toggled))
    (smoke-j4--check "toggle handler ran off the token" smoke-j4--toggled)
    (smoke-j4--drain 1)
    (smoke-j4--flush-idle-saves)
    (let ((text (smoke-j4--file-text)))
      (smoke-j4--check "fixture file carries * DONE on disk"
                       (string-search "* DONE Water the plants" text))
      (smoke-j4--check "state note flushed to LOGBOOK on disk"
                       (and (string-search ":LOGBOOK:" text)
                            (string-match-p
                             "- State \"DONE\" +from +\"TODO\"" text))))

    ;; Q3 capture lands in the file (org-capture-finalize saves itself).
    (smoke-j4--mark "Q3-TAP-CAPTURE")
    (smoke-j4--drain 150 (lambda ()
                           (string-search "From the phone"
                                          (smoke-j4--file-text))))
    (let ((text (smoke-j4--file-text)))
      (smoke-j4--check "captured title in the file on disk"
                       (string-search "* TODO From the phone" text))
      (smoke-j4--check "no template residue"
                       (not (string-search "%^" text)))
      (smoke-j4--check "no lingering capture buffer"
                       (not (cl-find-if
                             (lambda (b) (string-prefix-p "CAPTURE-"
                                                          (buffer-name b)))
                             (buffer-list)))))

    ;; Q4 the swept token answers stale.
    (smoke-j4--mark "Q4-TAP-STALE")
    (smoke-j4--drain 150 (lambda () smoke-j4--stale-answer))
    (smoke-j4--check "swept token answered stale"
                     (eq smoke-j4--stale-answer 'stale)
                     (format "%S" smoke-j4--stale-answer))

    ;; Owner teardown sweeps the live set too.
    (jetpacs-teardown-owner "ja4")
    (smoke-j4--drain 2)
    (smoke-j4--check "teardown swept the live token"
                     (null (jetpacs-org-token-ref smoke-j4--live-token
                                                  :owner "ja4"))))

  (ebp-client-close client 'smoke-done))

(when-let* ((buf (find-buffer-visiting smoke-j4--file)))
  ;; Never let kill-buffer raise a modified-buffer prompt in batch.
  (with-current-buffer buf (set-buffer-modified-p nil))
  (kill-buffer buf))
(delete-directory smoke-j4--dir t)

(princ (format "\n%s (%d failure(s))\n"
               (if (zerop smoke-j4--fails) "SMOKE PASS" "SMOKE FAIL")
               smoke-j4--fails))
(kill-emacs (if (zerop smoke-j4--fails) 0 1))

;;; smoke-ja4.el ends here
