;;; smoke-ja6.el --- JA-6 device gate, consolidated -*- lexical-binding: t; -*-

;; The files rung's hardware claims over ONE connection, WSL-driven
;; (the module runs here; paths are workstation paths; the tablet is
;; the screen and the finger):
;;   P1 browse: the dired card skin renders; a folder tap CDs through
;;      the guard; ".." returns to the landing.
;;   P2 grep: typing into the text_input submits (SPEC 14.3 `value'),
;;      the results screen pushes, and a hit tap opens the EDITOR.
;;   P3 editor: device typing + save lands on disk through
;;      jetpacs.files.save; a second save over an EXTERNALLY-changed
;;      file answers `stale' and clobbers nothing (the mtime stamp).
;;   P4 ops: back to the browser; long-press menu -> Duplicate
;;      (promptless); the row trash -> the Companion-NATIVE descriptor
;;      :confirm -> delete; long-press -> Rename -> the bridged
;;      read-string dialog -> the `absent'-guarded rename.
;;   P5 launcher: the apps button (a foreign-surface :any-surface tap)
;;      shows the launcher; its files row switches back.
;;
;; Run with the app open and `adb forward tcp:8765 tcp:8765'.
;; The runner performs each `*-TAP-*' mark as it prints.

(require 'ebp)
(require 'jetpacs-widgets)
(require 'jetpacs-async)
(require 'jetpacs-surfaces)
(require 'jetpacs-shell)
(require 'jetpacs-buffer)
(require 'jetpacs-dialog)
(require 'jetpacs-navigate)
(require 'jetpacs-chrome)
(require 'jetpacs-files)
(require 'jetpacs-launcher)

(defvar smoke-j6--fails 0)
(defun smoke-j6--check (label ok &optional detail)
  (princ (format "%-52s %s%s\n" label (if ok "PASS" "FAIL")
                 (if detail (format "  (%s)" detail) "")))
  (unless ok (setq smoke-j6--fails (1+ smoke-j6--fails))))
(defun smoke-j6--drain (secs &optional stop-fn)
  (let ((deadline (+ (float-time) secs)))
    (while (and (< (float-time) deadline)
                (not (and stop-fn (funcall stop-fn))))
      (accept-process-output nil 0.1))))
(defun smoke-j6--mark (m) (princ (concat m "\n")) (message "%s" m))
(defun smoke-j6--slurp (path)
  (with-temp-buffer (insert-file-contents path) (buffer-string)))

;; The fixture tree (generated bytes only).
(defvar smoke-j6--fix
  (file-name-as-directory (make-temp-file "smoke-ja6" t)))
(make-directory (concat smoke-j6--fix "alpha"))
(write-region "needle target\n" nil (concat smoke-j6--fix "alpha/inside.txt")
              nil 'silent)
(write-region "plain beta\n" nil (concat smoke-j6--fix "beta.txt") nil 'silent)
(write-region "* heading\n" nil (concat smoke-j6--fix "gamma.org") nil 'silent)

(setq jetpacs-files-roots (list smoke-j6--fix)
      jetpacs-files-default-dir smoke-j6--fix
      jetpacs-files-shared-storage nil
      jetpacs-files--shared-dir nil
      jetpacs-files--dir nil)

(let ((client
       (jetpacs-connect
        "127.0.0.1" 8765
        :client-name "wsl-emacs" :client-version "30.1"
        :pairing-id "101112131415161718191a1b1c1d1e1f"
        :token (ebp-decode-pairing-token "AAECAwQFBgcICQoLDA0ODw")
        :wants '("surfaces.dialog")
        :receipt-file (make-temp-file "smoke-j6-receipts")))
      (fixtrue (file-name-as-directory (file-truename smoke-j6--fix))))

  (smoke-j6--drain 20 (lambda () (jetpacs-connected-p)))
  (smoke-j6--check "session reaches READY" (jetpacs-connected-p))

  (when (jetpacs-connected-p)
    (smoke-j6--check "surfaces.dialog granted"
                     (jetpacs-granted-p "surfaces.dialog"))

    ;; P1 browse.
    (smoke-j6--check "files pushed"
                     (integerp (with-jetpacs-owner "jetpacs.files"
                                 (jetpacs-shell-push "jetpacs.files"))))
    (smoke-j6--drain 2)
    (smoke-j6--mark "P1-TAP-ALPHA")
    (smoke-j6--drain 150
                     (lambda ()
                       (equal jetpacs-files--dir (concat fixtrue "alpha/"))))
    (smoke-j6--check "folder tap CD'd through the guard"
                     (equal jetpacs-files--dir (concat fixtrue "alpha/"))
                     (format "%S" jetpacs-files--dir))
    (smoke-j6--mark "P1-TAP-UP")
    (smoke-j6--drain 150
                     (lambda () (equal jetpacs-files--dir fixtrue)))
    (smoke-j6--check "up row returned to the landing"
                     (equal jetpacs-files--dir fixtrue))

    ;; P2 grep -> hit -> editor.
    (smoke-j6--mark "P2-TYPE-SEARCH")
    (smoke-j6--drain 150
                     (lambda ()
                       (equal (jetpacs-chrome-stack "jetpacs.files")
                              '("grep" "browser"))))
    (smoke-j6--check "search submit pushed the results screen"
                     (equal (jetpacs-chrome-stack "jetpacs.files")
                            '("grep" "browser")))
    (smoke-j6--check "the request captured the typed literal"
                     (equal (plist-get jetpacs-files--grep-request :query)
                            "needle"))
    (smoke-j6--mark "P2-TAP-HIT")
    (smoke-j6--drain 150
                     (lambda ()
                       (equal (car (jetpacs-chrome-stack "jetpacs.files"))
                              "edit")))
    (smoke-j6--check "hit tap opened the editor screen"
                     (equal (car (jetpacs-chrome-stack "jetpacs.files"))
                            "edit"))
    (smoke-j6--check "editing the hit's file"
                     (equal (plist-get jetpacs-files--edit :path)
                            (concat fixtrue "alpha/inside.txt")))

    ;; P3 editor save + the mtime stale-guard.
    (let ((target (concat fixtrue "alpha/inside.txt")))
      (smoke-j6--mark "P3-TYPE-AND-SAVE")
      (smoke-j6--drain 150
                       (lambda ()
                         (string-search "EDITED" (smoke-j6--slurp target))))
      (smoke-j6--check "device save landed on disk"
                       (string-search "EDITED" (smoke-j6--slurp target))
                       (format "%S" (smoke-j6--slurp target)))
      ;; Change the file UNDERNEATH the open editor.
      (sleep-for 0.2)
      (write-region "EXTERNAL\n" nil target nil 'silent)
      (smoke-j6--mark "P3-TAP-SAVE-AGAIN")
      (smoke-j6--drain 12)
      (smoke-j6--check "stale save clobbered nothing"
                       (equal (smoke-j6--slurp target) "EXTERNAL\n")
                       (format "%S" (smoke-j6--slurp target))))

    ;; P4 the ops.
    (smoke-j6--mark "P4-TAP-BACK-TWICE")
    (smoke-j6--drain 150
                     (lambda ()
                       (equal (jetpacs-chrome-stack "jetpacs.files")
                              '("browser"))))
    (smoke-j6--check "back to the browser"
                     (equal (jetpacs-chrome-stack "jetpacs.files")
                            '("browser")))
    (smoke-j6--mark "P4-DUP-BETA")
    (smoke-j6--drain 150
                     (lambda ()
                       (file-exists-p (concat smoke-j6--fix "beta copy.txt"))))
    (smoke-j6--check "menu Duplicate created the copy"
                     (file-exists-p (concat smoke-j6--fix "beta copy.txt")))
    (smoke-j6--mark "P4-TRASH-COPY")
    (smoke-j6--drain 150
                     (lambda ()
                       (not (file-exists-p
                             (concat smoke-j6--fix "beta copy.txt")))))
    (smoke-j6--check "descriptor :confirm delete removed it"
                     (not (file-exists-p (concat smoke-j6--fix "beta copy.txt"))))
    (smoke-j6--mark "P4-RENAME-GAMMA")
    (smoke-j6--drain 200
                     (lambda ()
                       (and (file-exists-p (concat smoke-j6--fix "delta.org"))
                            (not (file-exists-p
                                  (concat smoke-j6--fix "gamma.org"))))))
    (smoke-j6--check "bridged rename moved gamma.org -> delta.org"
                     (and (file-exists-p (concat smoke-j6--fix "delta.org"))
                          (not (file-exists-p
                                (concat smoke-j6--fix "gamma.org")))))

    ;; P5 the launcher.
    (smoke-j6--mark "P5-TAP-APPS")
    (smoke-j6--drain 150
                     (lambda ()
                       (gethash "app:jetpacs.launcher"
                                jetpacs--applied-revisions)))
    (smoke-j6--check "apps button showed the launcher (:any-surface)"
                     (integerp (gethash "app:jetpacs.launcher"
                                        jetpacs--applied-revisions)))
    (let ((rev (gethash "app:jetpacs.files" jetpacs--applied-revisions)))
      (smoke-j6--mark "P5-TAP-FILES-ROW")
      (smoke-j6--drain 150
                       (lambda ()
                         (not (equal rev (gethash "app:jetpacs.files"
                                                  jetpacs--applied-revisions)))))
      (smoke-j6--check "launcher row switched back to files"
                       (not (equal rev (gethash "app:jetpacs.files"
                                                jetpacs--applied-revisions))))))

  (ebp-client-close client 'smoke-done))

(delete-directory smoke-j6--fix t)
(princ (format "\n%s (%d failure(s))\n"
               (if (zerop smoke-j6--fails) "SMOKE PASS" "SMOKE FAIL")
               smoke-j6--fails))
(kill-emacs (if (zerop smoke-j6--fails) 0 1))

;;; smoke-ja6.el ends here
