;;; smoke-files-sync.el --- P1-B device gate: live file editing -*- lexical-binding: t; -*-

;; MANUAL. NOT run by test/run-tests.sh, and it must not be: it dials a
;; real Companion on 127.0.0.1:8765, needs a tablet with the app open and
;; a finger on it, and blocks for minutes waiting for taps. Every suite
;; the runner drives is headless and hermetic; this one is neither.
;;
;; Run with the app open and the device reachable:
;;   adb -s "$ANDROID_SERIAL" forward tcp:8765 tcp:8765
;;   emacs -Q --batch -L emacs -l test/smoke-files-sync.el
;;
;; What it proves — the six behaviours the §19 editor exists for, over
;; ONE connection and ONE .el file:
;;   B1 device -> desktop: typing on the tablet reaches the Emacs BUFFER
;;      (not just a mirror string) as an `edit.apply' splice.
;;   B2 desktop -> device: an edit made HERE reaches the tablet, because
;;      track-changes sees it and it leaves as one splice.
;;   B3 completion: the dropdown offers jetpacs-/ebp- symbols, which
;;      only happens if the document id kept its extension and the
;;      shadow got `emacs-lisp-mode'.
;;   B4 diagnostics: an unbalanced paren draws a squiggle within
;;      `ebp-sync-diagnostics-delay' — flymake in the REAL buffer.
;;   B5 fontify: the colours are Emacs's font-lock ROLES, not the client
;;      tokenizer. Compare against smoke-syntax.el, which shows the
;;      tokenizer alone: a `defun' the tokenizer does not know still
;;      colours here.
;;   B6 eldoc: moving the caret onto a known symbol puts its signature
;;      in the doc line above the keyboard, and leaving it clears it.
;;   B7 save: the toolbar save writes the BUFFER to disk and leaves the
;;      desktop buffer unmodified — no revert, no echoed splice.
;;
;; The runner performs each `*-DO-*' mark as it prints and answers the
;; observation prompts; the elisp half asserts everything it can see.

(require 'ebp)
(require 'ebp-sync)
(require 'ebp-complete)
(require 'jetpacs-widgets)
(require 'jetpacs-async)
(require 'jetpacs-surfaces)
(require 'jetpacs-shell)
(require 'jetpacs-buffer)
(require 'jetpacs-navigate)
(require 'jetpacs-chrome)
(require 'jetpacs-files)

(defvar smoke-fs--fails 0)
(defun smoke-fs--check (label ok &optional detail)
  (princ (format "%-56s %s%s\n" label (if ok "PASS" "FAIL")
                 (if detail (format "  (%s)" detail) "")))
  (unless ok (setq smoke-fs--fails (1+ smoke-fs--fails))))
(defun smoke-fs--drain (secs &optional stop-fn)
  (let ((deadline (+ (float-time) secs)))
    (while (and (< (float-time) deadline)
                (not (and stop-fn (funcall stop-fn))))
      (accept-process-output nil 0.1))))
(defun smoke-fs--mark (m) (princ (concat m "\n")) (message "%s" m))

;; The fixture: one small elisp file, generated bytes only.
(defvar smoke-fs--fix
  (file-name-as-directory (make-temp-file "smoke-files-sync" t)))
(defvar smoke-fs--file (concat smoke-fs--fix "live.el"))
(write-region ";;; live.el --- fixture -*- lexical-binding: t; -*-\n\
(defun live-add (a b)\n\
  \"Add A and B.\"\n\
  (+ a b))\n"
              nil smoke-fs--file nil 'silent)

(setq jetpacs-files-roots (list smoke-fs--fix)
      jetpacs-files-default-dir smoke-fs--fix
      jetpacs-files-shared-storage nil
      jetpacs-files-sync-editor t)

(defun smoke-fs--buffer ()
  "The attached buffer, or nil."
  (plist-get jetpacs-files--edit :buffer))

(jetpacs-connect
 "127.0.0.1" 8765
 :client-name "wsl-emacs" :client-version "30.1"
 :pairing-id "101112131415161718191a1b1c1d1e1f"
 :token (ebp-decode-pairing-token "AAECAwQFBgcICQoLDA0ODw")
 :wants '("editor.sync" "theme" "surfaces.dialog" "presentation.snackbar")
 :receipt-file (make-temp-file "smoke-files-sync-receipts"))

(smoke-fs--drain 10 (lambda () (jetpacs-ready-p)))
(smoke-fs--check "session READY" (jetpacs-ready-p))
(smoke-fs--check "editor.sync granted" (jetpacs-granted-p "editor.sync"))

(jetpacs-shell-push jetpacs-files-owner)
(smoke-fs--drain 3)
(smoke-fs--mark "*-DO-1* tap live.el in the file list.")
(smoke-fs--drain 60 #'smoke-fs--buffer)

(smoke-fs--check "a real buffer is attached" (buffer-live-p (smoke-fs--buffer))
                 (buffer-name (smoke-fs--buffer)))
(smoke-fs--check "document id kept its extension"
                 (string-suffix-p ".el" (or (plist-get jetpacs-files--edit
                                                       :document) ""))
                 (plist-get jetpacs-files--edit :document))
(smoke-fs--check "the buffer is the FILE's buffer, in emacs-lisp-mode"
                 (with-current-buffer (smoke-fs--buffer)
                   (and (equal buffer-file-name (file-truename smoke-fs--file))
                        (eq major-mode 'emacs-lisp-mode))))

;; B1 — device to desktop.
(let ((before (with-current-buffer (smoke-fs--buffer) (buffer-string))))
  (smoke-fs--mark "*-DO-2* type `;; from the phone' on a new last line.")
  (smoke-fs--drain 90
                   (lambda ()
                     (with-current-buffer (smoke-fs--buffer)
                       (save-excursion
                         (goto-char (point-min))
                         (search-forward "from the phone" nil t)))))
  (smoke-fs--check "B1 device typing reached the desktop BUFFER"
                   (with-current-buffer (smoke-fs--buffer)
                     (and (not (equal (buffer-string) before))
                          (string-search "from the phone" (buffer-string))))))

;; B2 — desktop to device.
(with-current-buffer (smoke-fs--buffer)
  (goto-char (point-max))
  (insert ";; from emacs\n")
  (ebp-sync-flush))
(smoke-fs--drain 5)
(smoke-fs--mark "*-DO-3* confirm `;; from emacs' appeared on the tablet.")
(smoke-fs--drain 30)
(smoke-fs--check "B2 desktop edit left as one splice"
                 (with-current-buffer (smoke-fs--buffer)
                   (and (null ebp-sync--queue) (null ebp-sync--inflight))))

;; B3/B4/B5/B6 are the phone's eyes; the elisp half can only prove the
;; senders are live and the session is the one being annotated.
(smoke-fs--mark "*-DO-4* type `(jetpacs-' and confirm a dropdown of \
jetpacs- symbols.")
(smoke-fs--drain 45)
(smoke-fs--mark "*-DO-5* delete a closing paren; confirm a squiggle \
within ~4s.")
(smoke-fs--drain 45)
(smoke-fs--check "B4 flymake is running in the attached buffer"
                 (with-current-buffer (smoke-fs--buffer) flymake-mode))
(smoke-fs--mark "*-DO-6* restore the paren; confirm `defun' and the \
docstring carry Emacs's colours (smoke-syntax.el is the tokenizer-only \
comparison).")
(smoke-fs--drain 45)
(smoke-fs--check "B5 fontify runs are contract roles"
                 (with-current-buffer (smoke-fs--buffer)
                   (let ((runs (ebp-sync--fontify-runs)))
                     (and runs
                          (cl-every (lambda (r) (stringp (plist-get r :role)))
                                    runs)))))
(smoke-fs--mark "*-DO-7* tap inside `live-add'; confirm a signature in \
the line above the keyboard, then tap into whitespace and confirm it \
clears.")
(smoke-fs--drain 60)
(smoke-fs--check "B6 the eldoc rider is armed"
                 (and ebp-sync-eldoc
                      (with-current-buffer (smoke-fs--buffer)
                        (not (eq ebp-sync--eldoc-stamp 'unset)))))

;; B7 — the synchronized save.
(smoke-fs--mark "*-DO-8* tap the save icon.")
(smoke-fs--drain 60
                 (lambda ()
                   (string-search "from the phone"
                                  (with-temp-buffer
                                    (insert-file-contents smoke-fs--file)
                                    (buffer-string)))))
(smoke-fs--check "B7 the save wrote the BUFFER to disk"
                 (equal (with-temp-buffer
                          (insert-file-contents smoke-fs--file)
                          (buffer-string))
                        (with-current-buffer (smoke-fs--buffer)
                          (buffer-string))))
(smoke-fs--check "B7 the desktop buffer ends UNMODIFIED (no revert echo)"
                 (with-current-buffer (smoke-fs--buffer)
                   (not (buffer-modified-p))))

(princ (format "\nsmoke-files-sync: %d failure(s); fixture %s\n"
               smoke-fs--fails smoke-fs--fix))
(kill-emacs (if (zerop smoke-fs--fails) 0 1))
;;; smoke-files-sync.el ends here
