;;; smoke-ja5.el --- JA-5 device gate: org on screen -*- lexical-binding: t; -*-

;; Hardware claims over ONE connection, driving the REAL org modules
;; (no throwaway handlers — the verbs under test are the shipped ones).
;; A human performs the tap named at each mark; the script polls disk
;; and session state.  Steps, in order:
;;
;;   S1 render: the fixture renders through the skin onto app:ja5 —
;;      acceptance proves the native table/divider/data:-image passed
;;      the Companion's gates within budget.
;;   S2 CHECKBOX: tap the "[ ]" box -> the box flips AND the [/] cookie
;;      recounts, on disk.
;;   S3 DRAWER: tap the ":PROPERTIES:" line -> the drawer unfolds (the
;;      arm's jetpacs.buffer.fold through org-cycle).
;;   S4 FOOTNOTE: tap "[fn:1]" -> dialog; tap "Go to definition" ->
;;      the drill screen appears with the line-number snackbar.
;;   S5 SHEET+SCHEDULE: tap the "Tasks" heading -> sheet; Schedule… ->
;;      pick any date, repeater "+ every" 1 weeks -> Save -> SCHEDULED
;;      with +1w lands on disk (the pick's abandon+re-present ran).
;;   S6 ARCHIVE: tap "Second heading" -> sheet -> Archive -> device
;;      CONFIRM -> the subtree lands in the _archive file.
;;   S7 TIMESTAMP: tap the body date -> dialog seeded with it; pick a
;;      different date -> Save -> the stamp changed on disk.
;;   S8 ADD-HEADING: tap the "+ heading" button -> the bridged text
;;      dialog; type exactly  Phone note  -> OK -> "* Phone note" at
;;      the end of the file on disk.
;;   F1-F3 FILES: tap "Files", browse to ja5.org -> it opens RENDERED
;;      (the body seam); tap the edit icon -> the PLAIN editor with
;;      the org toolbar; toolbar Src -> emacs-lisp -> SAVE -> the
;;      block lands on disk.
;;   H1 HABITS: tap "Habits" -> the strip screen; tap Done on "Water
;;      the ficus habit" -> the repeater advances on disk.
;;   T  teardown: ja5's owner sweep tombstones its surface; the
;;      jetpacs.org sweep clears any live timestamp sessions.
;;
;; Stale/rejected paths are ERT-pinned (the JA-4 smoke proved token
;; staleness on hardware); this gate spends its taps on the new
;; surface area.  Run with the app open and
;; `adb forward tcp:8765 tcp:8765'.

(require 'ebp)
(require 'org)
(require 'jetpacs-widgets)
(require 'jetpacs-surfaces)
(require 'jetpacs-shell)
(require 'jetpacs-chrome)
(require 'jetpacs-navigate)
(require 'jetpacs-launcher)
(require 'jetpacs-files)
(require 'jetpacs-org)
(require 'jetpacs-org-render)   ; pulls jetpacs-org-dialogs
(require 'jetpacs-org-toolbar)
(require 'jetpacs-org-habits)

(defvar smoke-j5--fails 0)
(defun smoke-j5--check (label ok &optional detail)
  (princ (format "%-52s %s%s\n" label (if ok "PASS" "FAIL")
                 (if detail (format "  (%s)" detail) "")))
  (unless ok (setq smoke-j5--fails (1+ smoke-j5--fails))))
(defun smoke-j5--drain (secs &optional stop-fn)
  (let ((deadline (+ (float-time) secs)))
    (while (and (< (float-time) deadline)
                (not (and stop-fn (funcall stop-fn))))
      (accept-process-output nil 0.1))))
(defun smoke-j5--mark (m) (princ (concat m "\n")) (message "%s" m))

;;; Fixtures: generated bytes only, under one root everything accepts.

(defvar smoke-j5--dir (file-name-as-directory
                       (file-truename (make-temp-file "smoke-ja5" t))))
(defvar smoke-j5--file (expand-file-name "ja5.org" smoke-j5--dir))
(defvar smoke-j5--habits (expand-file-name "habits.org" smoke-j5--dir))

(with-temp-file smoke-j5--file
  (insert "* Tasks [/]\n"
          ":PROPERTIES:\n:ID: ja5-fix-1\n:END:\n"
          "- [ ] water the ficus\n"
          "A note[fn:1] and a date <2026-08-15 Sat>.\n\n"
          "| Item | Qty |\n|------+-----|\n| pots | 3 |\n\n"
          "-----\n\n"
          "[[file:img.png]]\n\n"
          "[fn:1] The footnote definition lives here.\n"
          "* Second heading\nbody two\n"))
(with-temp-file smoke-j5--habits
  (insert "* TODO Water the ficus habit\n"
          "SCHEDULED: <2026-07-20 Mon .+2d>\n"
          ":PROPERTIES:\n:STYLE:    habit\n:END:\n"))
(let ((coding-system-for-write 'binary))
  (write-region
   (base64-decode-string
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==")
   nil (expand-file-name "img.png" smoke-j5--dir)))

(setq jetpacs-org-roots (list smoke-j5--dir)
      org-agenda-files (list smoke-j5--habits)
      jetpacs-files-roots (list smoke-j5--dir))

(defun smoke-j5--text (file)
  (with-temp-buffer (insert-file-contents file) (buffer-string)))

(defun smoke-j5--flush-idle-saves ()
  (dolist (tm (copy-sequence timer-idle-list))
    (when (eq (timer--function tm) #'jetpacs-org--save-now)
      (cancel-timer tm)
      (apply (timer--function tm) (timer--args tm)))))

;;; The ja5 host screen: the rendered fixture + the nav affordances.

(defvar smoke-j5--buf (find-file-noselect smoke-j5--file))
(with-current-buffer smoke-j5--buf
  (unless (derived-mode-p 'org-mode) (org-mode)))

(with-jetpacs-owner "ja5"
  (jetpacs-chrome-define-root
   "ja5" "org"
   (lambda (_back)
     (jetpacs-chrome-screen
      "JA-5 org smoke"
      (apply #'jetpacs-column
             (append
              (list (jetpacs-row
                     (jetpacs-button
                      "+ heading"
                      (jetpacs-org-add-heading-descriptor
                       (buffer-name smoke-j5--buf))
                      :variant "tonal")
                     (jetpacs-button "Habits"
                                     (jetpacs-action "ja5.habits")
                                     :variant "tonal")
                     (jetpacs-launcher-button)
                     :spacing 8))
              (jetpacs-render-buffer smoke-j5--buf))))))
  (jetpacs-defaction "ja5.habits"
    (lambda (_args _params)
      (jetpacs-flow-continue
       (lambda ()
         (condition-case err
             (jetpacs-shell-push "jetpacs.org")
           (error (message "smoke-ja5: habits push failed: %s"
                           (jetpacs--error-label err))))))
      'accepted)))

;;; The run.

(let ((client
       (jetpacs-connect
        "127.0.0.1" 8765
        :client-name "wsl-emacs" :client-version "30.1"
        :pairing-id "101112131415161718191a1b1c1d1e1f"
        :token (ebp-decode-pairing-token "AAECAwQFBgcICQoLDA0ODw")
        :receipt-file (make-temp-file "smoke-j5-receipts"))))

  (smoke-j5--drain 20 (lambda () (jetpacs-connected-p)))
  (smoke-j5--check "session reaches READY" (jetpacs-connected-p))

  (when (jetpacs-connected-p)
    ;; S1: the skin's output — table, divider, data: image — is accepted.
    (let ((pushed (with-jetpacs-owner "ja5"
                    (condition-case err
                        (progn (jetpacs-shell-push "ja5") t)
                      (error (message "push signal: %s"
                                      (jetpacs--error-label err))
                             nil)))))
      (smoke-j5--check "S1 skin surface accepted (table+rule+image)"
                       pushed))
    (smoke-j5--drain 2)

    ;; S2 checkbox.
    (smoke-j5--mark "S2-TAP-THE-CHECKBOX [ ]")
    (smoke-j5--drain 180 (lambda ()
                           (smoke-j5--flush-idle-saves)
                           (string-search "[X] water"
                                          (smoke-j5--text smoke-j5--file))))
    (let ((text (smoke-j5--text smoke-j5--file)))
      (smoke-j5--check "S2 checkbox flipped on disk"
                       (string-search "- [X] water the ficus" text))
      (smoke-j5--check "S2 statistics cookie recounted"
                       (string-search "* Tasks [1/1]" text)))

    ;; S3 drawer fold tap.  The claim is the TRANSITION, so the folded
    ;; precondition is asserted first — a drawer that starts visible
    ;; would satisfy the poll before any tap and prove nothing.
    (let ((id-visible
           (lambda ()
             (with-current-buffer smoke-j5--buf
               (org-with-wide-buffer
                (goto-char (point-min))
                (search-forward ":ID:" nil t)
                (let ((iv (get-char-property (match-beginning 0)
                                             'invisible)))
                  (not (and iv (invisible-p iv)))))))))
      (unless (funcall id-visible)
        (smoke-j5--check "S3 precondition: drawer starts folded" t))
      (when (funcall id-visible)
        ;; Fold it ourselves so the tap still has a transition to prove.
        (with-current-buffer smoke-j5--buf
          (org-with-wide-buffer
           (goto-char (point-min))
           (search-forward ":PROPERTIES:")
           (beginning-of-line)
           (org-cycle)))
        (smoke-j5--check "S3 precondition: drawer folded by harness"
                         (not (funcall id-visible))))
      (smoke-j5--mark "S3-TAP-THE-:PROPERTIES:-LINE")
      (smoke-j5--drain 180 id-visible)
      (smoke-j5--check "S3 drawer unfolded (org-cycle via fold verb)"
                       (funcall id-visible)))

    ;; S4 footnote dialog -> drill.
    (smoke-j5--mark "S4-TAP-[fn:1]-THEN-'Go to definition'")
    (smoke-j5--drain 240 (lambda ()
                           (> (length (jetpacs-chrome-stack "ja5")) 1)))
    (smoke-j5--check "S4 definition drill screen pushed"
                     (> (length (jetpacs-chrome-stack "ja5")) 1)
                     (format "stack %S" (jetpacs-chrome-stack "ja5")))

    ;; S5 sheet -> Schedule with a repeater.
    (smoke-j5--mark
     "S5-TAP-'Tasks'-HEADING->Schedule…->date+repeat-1w->Save")
    (smoke-j5--drain 300 (lambda ()
                           (smoke-j5--flush-idle-saves)
                           (string-search "+1w>"
                                          (smoke-j5--text smoke-j5--file))))
    (let ((text (smoke-j5--text smoke-j5--file)))
      (smoke-j5--check "S5 SCHEDULED landed on disk"
                       (string-search "SCHEDULED: <" text))
      (smoke-j5--check "S5 repeater survived the cookie surgery"
                       (string-search "+1w>" text)))

    ;; S6 archive with the device confirm.
    (smoke-j5--mark "S6-TAP-'Second heading'->Archive->CONFIRM")
    (smoke-j5--drain 300 (lambda ()
                           (file-exists-p (concat smoke-j5--file
                                                  "_archive"))))
    (smoke-j5--check "S6 archive file exists"
                     (file-exists-p (concat smoke-j5--file "_archive")))
    (when (file-exists-p (concat smoke-j5--file "_archive"))
      (smoke-j5--check "S6 subtree moved into it"
                       (string-search "Second heading"
                                      (smoke-j5--text
                                       (concat smoke-j5--file "_archive")))))

    ;; S7 the body timestamp.
    (smoke-j5--mark "S7-TAP-THE-BODY-DATE->pick-another->Save")
    (smoke-j5--drain 300 (lambda ()
                           (smoke-j5--flush-idle-saves)
                           (not (string-search
                                 "<2026-08-15"
                                 (smoke-j5--text smoke-j5--file)))))
    (smoke-j5--check "S7 body stamp rewritten on disk"
                     (not (string-search "<2026-08-15"
                                         (smoke-j5--text smoke-j5--file))))

    ;; S8 add-heading through the bridged prompt.
    (smoke-j5--mark "S8-TAP-'+ heading'->type-exactly:-Phone note->OK")
    (smoke-j5--drain 300 (lambda ()
                           (string-search "* Phone note"
                                          (smoke-j5--text smoke-j5--file))))
    (smoke-j5--check "S8 heading appended on disk"
                     (string-search "* Phone note"
                                    (smoke-j5--text smoke-j5--file)))

    ;; F1-F3 the files path: rendered view, plain toggle, toolbar.
    (smoke-j5--mark
     "F1-TAP-Apps->Files->ja5.org (should open RENDERED, no editor)")
    (smoke-j5--drain 300 (lambda ()
                           (member "edit"
                                   (jetpacs-chrome-stack "jetpacs.files"))))
    (smoke-j5--check "F1 files edit screen reached"
                     (member "edit" (jetpacs-chrome-stack "jetpacs.files")))
    (smoke-j5--mark "F2-TAP-THE-EDIT-(pencil)-ICON")
    (smoke-j5--drain 240 (lambda ()
                           (eq (gethash (file-truename smoke-j5--file)
                                        jetpacs-org-render--files-mode)
                               'plain)))
    (smoke-j5--check "F2 view mode flipped to plain"
                     (eq (gethash (file-truename smoke-j5--file)
                                  jetpacs-org-render--files-mode)
                         'plain))
    (smoke-j5--mark "F3-TOOLBAR:Src->emacs-lisp-THEN-SAVE")
    (smoke-j5--drain 300 (lambda ()
                           (string-search "#+begin_src emacs-lisp"
                                          (smoke-j5--text smoke-j5--file))))
    (smoke-j5--check "F3 toolbar splice saved to disk"
                     (string-search "#+begin_src emacs-lisp"
                                    (smoke-j5--text smoke-j5--file)))

    ;; H1 habits.
    (smoke-j5--mark "H1-BACK->TAP-'Habits'->TAP-'Done'")
    (smoke-j5--drain 300 (lambda ()
                           (smoke-j5--flush-idle-saves)
                           (not (string-search
                                 "<2026-07-20"
                                 (smoke-j5--text smoke-j5--habits)))))
    (smoke-j5--check "H1 habit repeater advanced on disk"
                     (not (string-search "<2026-07-20"
                                         (smoke-j5--text smoke-j5--habits))))

    ;; T teardown.
    (smoke-j5--mark "T-TEARDOWN")
    (jetpacs-teardown-owner "ja5")
    (jetpacs-teardown-owner "jetpacs.org")
    (smoke-j5--drain 2)
    (smoke-j5--check "T ja5 surface swept from the roots"
                     (not (assoc "app:ja5" (jetpacs-shell-roots))))
    (smoke-j5--check "T timestamp sessions swept"
                     (zerop (hash-table-count
                             jetpacs-org-dialogs--ts-sessions))))

  (ebp-client-close client 'smoke-done))

(dolist (f (list smoke-j5--file smoke-j5--habits
                 (concat smoke-j5--file "_archive")))
  (when-let* ((buf (find-buffer-visiting f)))
    (with-current-buffer buf (set-buffer-modified-p nil))
    (kill-buffer buf)))
(delete-directory smoke-j5--dir t)

(princ (format "\n%s (%d failure(s))\n"
               (if (zerop smoke-j5--fails) "SMOKE PASS" "SMOKE FAIL")
               smoke-j5--fails))
(kill-emacs (if (zerop smoke-j5--fails) 0 1))

;;; smoke-ja5.el ends here
