#!/usr/bin/env python3
"""Generate STATE-REFERENCE.org's stateful-node inventory from contract.json.

The inventory enumerates every node type whose schema carries local UI
state or state hooks — derived member-by-member from
`ebp/contract.json`'s `node_schema`, never transcribed.  The prose
around the table cites the SPEC sections that own the semantics instead
of restating them.

Regenerate after any contract change:

    python3 docs/lookup-tables/generate-state-table.py

Content below the sentinel line is hand-authored and preserved verbatim.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(HERE, "STATE-REFERENCE.org")
SENTINEL = ("# >>> HAND-AUTHORED BELOW — proposals / ideation; "
            "not implemented; preserved verbatim by the generator")

STATE_MEMBERS = ["value", "on_change", "on_submit", "on_save",
                 "publish_state", "selected", "checked", "open"]


def main():
    contract = json.load(open(os.path.join(ROOT, "ebp", "contract.json")))
    schema = contract["node_schema"]

    tail = ""
    if os.path.exists(OUT):
        old = open(OUT, encoding="utf-8").read()
        if SENTINEL in old:
            tail = old[old.index(SENTINEL):]

    rows = []
    for node in sorted(schema):
        members = set(schema[node].get("required", [])
                      + schema[node].get("optional", []))
        present = [m for m in STATE_MEMBERS if m in members]
        if present and ("id" in members or "value" in present
                        or any(m.startswith("on_") for m in present)):
            rows.append((node,
                         "required" if "id" in schema[node]["required"]
                         else ("optional" if "id" in members else "—"),
                         present))

    w = []
    w.append("# -*- mode: org; coding: utf-8 -*-")
    w.append("#+TITLE: Jetpacs State Management Reference")
    w.append("#+AUTHOR: GENERATED by generate-state-table.py — do not edit above the sentinel")
    w.append("#+STARTUP: showall")
    w.append("#+OPTIONS: ^:nil")
    w.append("")
    w.append("* Jetpacs State Management Reference")
    w.append("")
    w.append("GENERATED from =ebp/contract.json='s =node_schema=.  The semantics")
    w.append("live in the SPEC and are cited, not restated: input-state")
    w.append("reconciliation and drafts are §13.6/§14.5–14.6, the welcome's")
    w.append("=input_state= merge is §10.3 step 2, =state.changed= ordering is")
    w.append("§14.6/§23.4, =reset_input_ids= is §13.2, and mid-session revision")
    w.append("floors absorb per §13.2 (amendment #148).  =contract.json= is")
    w.append("authoritative; this table is orientation (SPEC §24.4).")
    w.append("")
    w.append(f"** Stateful-node inventory ({len(rows)} node types)")
    w.append("")
    w.append("| Node | =id= | State members present |")
    w.append("|---|---|---|")
    for node, idp, present in rows:
        w.append(f"| ={node}= | {idp} | "
                 + ", ".join(f"={m}=" for m in present) + " |")
    w.append("")
    body = "\n".join(w)
    body += ("\n" + tail) if tail else "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print(f"wrote {OUT}; {len(rows)} stateful node types")


if __name__ == "__main__":
    main()
