#!/usr/bin/env python3
"""Generate ACTION-REFERENCE.org from contract.json + NodeSupport.kt + a live Emacs.

Every fact in the output is derived, not transcribed:

- the ActionDescriptor member tables come from `ebp/contract.json`'s
  `actions` registry (descriptor fields, offline policies, per-builtin
  required/optional schemas);
- the advertisement column comes from the Kotlin renderer's own
  `NodeSupport.APP_BUILTINS` / `DIALOG_BUILTINS` sets;
- the elisp examples are EXECUTED through `jetpacs-action` in a batch
  Emacs, and the wire payloads shown are `json-serialize` of what the
  constructor actually returned.  An example that stops building fails
  the generator — the doc cannot drift from the API.

Regenerate after any change to contract.json, NodeSupport.kt, or
jetpacs-widgets.el's constructors:

    python3 docs/lookup-tables/generate-action-table.py

Content below the sentinel line (if any) is hand-authored and preserved
verbatim.
"""

import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(HERE, "ACTION-REFERENCE.org")
SENTINEL = ("# >>> HAND-AUTHORED BELOW — proposals / ideation; "
            "not implemented; preserved verbatim by the generator")

EXAMPLES = [
    '(jetpacs-action "note.open" :args \'(:id "20260731T120000"))',
    '(jetpacs-action "note.save" :when-offline "queue" :ttl-s 3600'
    ' :dedupe "note:20260731T120000")',
    '(jetpacs-action "heading.todo-set" :args \'(:state "DONE")'
    ' :confirm "Mark this item done?")',
    '(jetpacs-action "note.search" :capture-fields \'("q"))',
]

BUILTIN_EXAMPLE = '(:builtin "view.switch" :view "profile")'


def run_examples():
    """Execute every example form in batch Emacs; return (form, plist, json)."""
    forms = "\n".join(
        f'(let ((v {form}))'
        f'  (princ (format "%S\\n" v))'
        f'  (princ (json-serialize v)) (princ "\\n"))'
        for form in EXAMPLES)
    builtin = (f'(princ (json-serialize \'{BUILTIN_EXAMPLE}))'
               f'(princ "\\n")')
    script = f'(progn (require \'jetpacs-widgets) {forms} {builtin})'
    proc = subprocess.run(
        ["emacs", "-Q", "--batch", "-L", os.path.join(ROOT, "emacs"),
         "--eval", script],
        capture_output=True, text=True, cwd=ROOT)
    if proc.returncode != 0:
        sys.exit(f"FATAL: an example no longer builds:\n{proc.stderr}")
    lines = [l for l in proc.stdout.splitlines() if l.strip()]
    if len(lines) != 2 * len(EXAMPLES) + 1:
        sys.exit(f"FATAL: unexpected example output:\n{proc.stdout}")
    trios = [(EXAMPLES[i], lines[2 * i], lines[2 * i + 1])
             for i in range(len(EXAMPLES))]
    return trios, lines[-1]


def kotlin_sets():
    path = os.path.join(
        ROOT, "companion/app/src/main/kotlin/com/calebc42/ebp/companion/"
        "render/NodeSupport.kt")
    src = open(path, encoding="utf-8").read()
    out = {}
    for name in ("APP_BUILTINS", "DIALOG_BUILTINS"):
        m = re.search(name + r"[^=]*=\s*sortedSetOf\(([^)]*)\)", src, re.S)
        if not m:
            sys.exit(f"FATAL: {name} not found in NodeSupport.kt")
        out[name] = set(re.findall(r'"([a-z_.]+)"', m.group(1)))
    return out


def esc(s):
    return s.replace("|", "\\vert{}")


def main():
    contract = json.load(open(os.path.join(ROOT, "ebp", "contract.json")))
    actions = contract["actions"]
    schema = actions["schema"]
    sets = kotlin_sets()
    trios, builtin_json = run_examples()

    tail = ""
    if os.path.exists(OUT):
        old = open(OUT, encoding="utf-8").read()
        if SENTINEL in old:
            tail = old[old.index(SENTINEL):]

    w = []
    w.append("# -*- mode: org; coding: utf-8 -*-")
    w.append("#+TITLE: Jetpacs Action Reference")
    w.append("#+AUTHOR: GENERATED by generate-action-table.py — do not edit above the sentinel")
    w.append("#+STARTUP: showall")
    w.append("#+OPTIONS: ^:nil")
    w.append("")
    w.append("* Jetpacs Action Reference")
    w.append("")
    w.append("GENERATED from =ebp/contract.json= (the =actions= registry), the")
    w.append("renderer's =NodeSupport.kt= advertisement sets, and examples")
    w.append("*executed* through =jetpacs-action= in a batch Emacs — the wire")
    w.append("payloads below are =json-serialize= of real constructor output.")
    w.append("=contract.json= is authoritative; this table is orientation")
    w.append("(SPEC §24.4: a projection gates shapes, never behavior).")
    w.append("")
    w.append("** 1. Remote ActionDescriptor (SPEC §14.1)")
    w.append("")
    w.append("Constructor: =jetpacs-action= (jetpacs-widgets.el).  An action name")
    w.append("MUST be a §4.4 namespaced identifier containing at least one dot;")
    w.append("dotless names are rejected at build time.")
    w.append("")
    remote = schema["remote"]
    w.append("| Member | Presence | Notes |")
    w.append("|---|---|---|")
    for m in remote["required"]:
        w.append(f"| ={m}= | required | — |")
    notes = {
        "when_offline": "one of =%s=; default =%s=" % (
            "= / =".join(actions["offline_policies"]),
            actions["offline_default"]),
        "ttl_s": "REQUIRED for =queue=/=wake=; forbidden for =drop=",
        "dedupe": "identifier; forbidden for =drop=; the key space is flat "
                  "per pairing identity (SPEC §15.2, amendment #144)",
        "confirm": "non-empty string; native confirmation before the event",
        "capture_fields": "distinct stateful widget IDs captured atomically",
        "args": "plain application data (object)",
    }
    for m in remote["optional"]:
        w.append(f"| ={m}= | optional | {notes.get(m, '—')} |")
    w.append("")
    w.append("** 2. Executed examples")
    w.append("")
    w.append("Each row was built by the generator in a live batch Emacs; if a")
    w.append("form stops building, generation fails.")
    w.append("")
    for form, plist, wire in trios:
        w.append(f"- Form: ={esc(form)}=")
        w.append(f"  - Result: ={esc(plist)}=")
        w.append(f"  - Wire: ={esc(wire)}=")
    w.append("")
    w.append("** 3. Local builtins")
    w.append("")
    w.append("There is NO =jetpacs-builtin= constructor: builtins are authored as")
    w.append("literal plists on a hook, e.g. =:on_tap " + BUILTIN_EXAMPLE + "=,")
    w.append(f"which serializes to ={esc(builtin_json)}=.")
    w.append("")
    w.append("| Builtin | Required members | Optional members | Advertised by |")
    w.append("|---|---|---|---|")
    for name in sorted(k for k in schema if k != "remote"):
        row = schema[name]
        req = ", ".join(f"={m}=" for m in row["required"]) or "—"
        opt = ", ".join(f"={m}=" for m in row["optional"]) or "—"
        adv = []
        if name in sets["APP_BUILTINS"]:
            adv.append("app profile")
        if name in sets["DIALOG_BUILTINS"]:
            adv.append("dialog profile")
        w.append(f"| ={name}= | {req} | {opt} | {', '.join(adv) or '—'} |")
    w.append("")
    body = "\n".join(w)
    if tail:
        body += "\n" + tail
    else:
        body += "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
